using SoftFocusBackend.Users.Domain.Model.Aggregates;
using SoftFocusBackend.Users.Domain.Model.Commands;
using SoftFocusBackend.Users.Interfaces.REST.Resources;

namespace SoftFocusBackend.Users.Interfaces.REST.Transform;

public static class UserResourceAssembler
{
    public static UserProfileResource ToProfileResource(User user)
    {
        return new UserProfileResource
        {
            Id = user.Id,
            Email = user.Email,
            FullName = user.FullName,
            FirstName = user.FirstName,
            LastName = user.LastName,
            UserType = user.UserType,
            DateOfBirth = user.DateOfBirth,
            Gender = user.Gender,
            Phone = user.Phone,
            ProfileImageUrl = user.ProfileImageUrl,
            Bio = user.Bio,
            Country = user.Country,
            City = user.City,
            Interests = user.Interests,
            MentalHealthGoals = user.MentalHealthGoals,
            EmailNotifications = user.EmailNotifications,
            PushNotifications = user.PushNotifications,
            IsProfilePublic = user.IsProfilePublic,
            IsActive = user.IsActive,
            LastLogin = user.LastLogin,
            CreatedAt = user.CreatedAt,
            UpdatedAt = user.UpdatedAt
        };
    }

    public static UpdateUserProfileCommand ToUpdateCommandWithImage(UpdateUserProfileResource resource, string userId, string currentFullName, byte[]? imageBytes = null, string? imageFileName = null)
    {
        // Calculate FullName from FirstName and LastName if provided, otherwise keep current
        string fullName = currentFullName;
        if (!string.IsNullOrWhiteSpace(resource.FirstName) || !string.IsNullOrWhiteSpace(resource.LastName))
        {
            var firstName = resource.FirstName?.Trim() ?? string.Empty;
            var lastName = resource.LastName?.Trim() ?? string.Empty;
            fullName = $"{firstName} {lastName}".Trim();

            // If fullName is empty after trim, keep the current one
            if (string.IsNullOrWhiteSpace(fullName))
            {
                fullName = currentFullName;
            }
        }

        return new UpdateUserProfileCommand(
            userId: userId,
            fullName: fullName,
            firstName: resource.FirstName,
            lastName: resource.LastName,
            dateOfBirth: resource.DateOfBirth,
            gender: resource.Gender,
            phone: resource.Phone,
            bio: resource.Bio,
            country: resource.Country,
            city: resource.City,
            interests: resource.Interests,
            mentalHealthGoals: resource.MentalHealthGoals,
            emailNotifications: resource.EmailNotifications,
            pushNotifications: resource.PushNotifications,
            isProfilePublic: resource.IsProfilePublic,
            profileImageUrl: null, // ProfileImageUrl is generated by Cloudinary after upload, not sent from client
            profileImageBytes: imageBytes,
            profileImageFileName: imageFileName
        );
    }

    public static object ToAdminUserResource(User user)
    {
        return new
        {
            id = user.Id,
            email = user.Email,
            fullName = user.FullName,
            userType = user.UserType.ToString(),
            isActive = user.IsActive,
            lastLogin = user.LastLogin,
            createdAt = user.CreatedAt,
            isVerified = user is PsychologistUser psychologist ? psychologist.IsVerified : (bool?)null
        };
    }

    public static object ToAdminUserDetailResource(User user)
    {
        var baseResource = new
        {
            id = user.Id,
            email = user.Email,
            fullName = user.FullName,
            firstName = user.FirstName,
            lastName = user.LastName,
            userType = user.UserType.ToString(),
            dateOfBirth = user.DateOfBirth,
            gender = user.Gender,
            phone = user.Phone,
            profileImageUrl = user.ProfileImageUrl,
            bio = user.Bio,
            country = user.Country,
            city = user.City,
            interests = user.Interests,
            mentalHealthGoals = user.MentalHealthGoals,
            emailNotifications = user.EmailNotifications,
            pushNotifications = user.PushNotifications,
            isProfilePublic = user.IsProfilePublic,
            isActive = user.IsActive,
            lastLogin = user.LastLogin,
            createdAt = user.CreatedAt,
            updatedAt = user.UpdatedAt
        };

        if (user is PsychologistUser psychologist)
        {
            return new
            {
                user = baseResource,
                psychologistData = new
                {
                    licenseNumber = psychologist.LicenseNumber,
                    professionalCollege = psychologist.ProfessionalCollege,
                    collegeRegion = psychologist.CollegeRegion,
                    university = psychologist.University,
                    graduationYear = psychologist.GraduationYear,
                    specialties = psychologist.Specialties,
                    yearsOfExperience = psychologist.YearsOfExperience,
                    isVerified = psychologist.IsVerified,
                    verificationDate = psychologist.VerificationDate,
                    verifiedBy = psychologist.VerifiedBy,
                    verificationNotes = psychologist.VerificationNotes,
                    currentPatientsCount = psychologist.CurrentPatientsCount,
                    isAcceptingNewPatients = psychologist.IsAcceptingNewPatients,
                    documents = new
                    {
                        licenseDocumentUrl = psychologist.LicenseDocumentUrl,
                        diplomaCertificateUrl = psychologist.DiplomaCertificateUrl,
                        identityDocumentUrl = psychologist.IdentityDocumentUrl,
                        additionalCertificatesUrls = psychologist.AdditionalCertificatesUrls
                    }
                }
            };
        }

        return new { user = baseResource };
    }

    public static object ToErrorResponse(string message, string? details = null)
    {
        return new
        {
            error = true,
            message,
            details,
            timestamp = DateTime.UtcNow
        };
    }
}